name: Move Post Every Minute

on:
  schedule:
    - cron: '* * * * *'

jobs:
  move_post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        node-version: '16'  # Specify Node.js version 16

    - name: Choose post to move
      run: |
        POSTS_DIR="scheduled_posts"  # Adjust the path if necessary
        TARGET_DIR="_posts"  # Adjust the path if necessary

        # Choose the post with the earliest creation time
        POST_TO_MOVE=$(ls -1t $POSTS_DIR | head -n 1)
        mv "$POSTS_DIR/$POST_TO_MOVE" $TARGET_DIR

        # Log information about the moved post
        echo "Moved post: $POST_TO_MOVE" >> moved_posts.log

    - name: Commit and push changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Move post to target directory"
        git push

    - name: Update log file
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git fetch
        git merge origin/main  # Adjust the branch name if necessary
        echo "Updated log at $(date)" >> moved_posts.log
        git add moved_posts.log
        git commit -m "Update moved_posts.log"
        git push
