name: Move Post Every Minute

on:
  schedule:
    - cron: '* * * * *'

jobs:
  move_post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Choose post to move
      run: |
        POSTS_DIR="../scheduled_posts"
        TARGET_DIR="../target_directory"  # Replace with the actual target directory path

        # Choose the post with the earliest creation time
        POST_TO_MOVE=$(ls -1t $POSTS_DIR | head -n 1)
        mv "$POSTS_DIR/$POST_TO_MOVE" $TARGET_DIR

        # Log information about the moved post
        echo "Moved post: $POST_TO_MOVE" >> moved_posts.log

    - name: Commit and push changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Move post to target directory"
        git push

    - name: Update log file
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git pull  # Ensure you have the latest changes
        echo "Updated log at $(date)" >> moved_posts.log
        git add moved_posts.log
        git commit -m "Update moved_posts.log"
        git push
